version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: start
    ports:
      - 4000:4000
    networks:
      net1:
        aliases:
          - web-server
    hostname: web-server
  worker-1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: start
    networks:
      net1:
        aliases:
          - worker-1
    hostname: worker-1
    depends_on:
      - web
  worker-2:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: start
    networks:
      net1:
        aliases:
          - worker-2
    hostname: worker-2
    depends_on:
      - web
  worker-3:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: start
    networks:
      net1:
        aliases:
          - worker-3
    hostname: worker-3
    depends_on:
      - web
networks:
  net1:
    driver: bridge
